image Say_Trash_Place_Wires:
    "./images/bg/Outdoor/Trash_Place/Day/wires/0000.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0001.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0002.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0003.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0004.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0005.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0006.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0007.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0008.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0009.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0010.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0011.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0012.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0013.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0014.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0015.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0016.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0017.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0018.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0019.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0020.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0021.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0022.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0023.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0024.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0025.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0026.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0027.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0028.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0029.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0030.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0031.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0032.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0033.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0034.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0035.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0036.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0037.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0038.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0039.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0040.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0041.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0042.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0043.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0044.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0045.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0046.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0047.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0048.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0049.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0050.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0051.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0052.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0053.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0054.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0055.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0056.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0057.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0058.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0059.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0060.png"
    0.1
    "./images/bg/Outdoor/Trash_Place/Day/wires/0061.png"
    0.1
    repeat
